<ul id="tabNodeDomainsList" class="unstyled jsLineColor cssTab">
    <? foreach ($this->html('domains') as $domainId => $domain): ?>
        <li id="tabNodeDomainsListEntry-<?= $domainId ?>" class="row-fluid cssLine jsLine">
            <a href="<?= $this->url(array($domain->html('name')), 'domaindetail') ?>"
               title="<?= $domain->html('name') ?>" class="span8">
                <?= $domain->html('name') ?>
            </a>
            <a href="<?= $this->url(array($domain->html('client/_id'), $domain->html('client/label')), 'clientDetail') ?>"
               class="pull-right jsClientOnDomain">
                <?= $domain->html('client/label') ?>
            </a>
        </li>
    <? endforeach; ?>
</ul>
