<div class="cssUserInfo grid_16">
    <ul class="cssUserInfo">
        <li>
            <a href="<?= $this->url(array(), 'profile') ?>"
               title="<?= $this->translate('My profile') ?>"
               class="cssUserName jsUserName" id="jsColorboxShort">

                <? if($this->toBool('identity/avatar')): ?>
                    <img id="jsAvatar" name="avatar" 
                         src="<?= $this->urlAvatar($this->html('identity/_id'), 50); ?>" />
                <? else: ?>
                    <img id="jsAvatar" name="avatar" 
                         src="<?= $this->baseUrl() ?>/img/dummy_user_50.png" 
                         alt="<?= $this->translate('avatar') ?>" />
                <? endif; ?>
                
                <?= $this->html('identity/label') ?>
            </a>
            
            <span>
                <a class="cssUserInfoButton">
                    <span class="cssUserInfoButton jsUserInfoButton">
                        <?= $this->translate('options') ?>
                    </span>
                </a>
            </span>
        </li>
    </ul>
    <div class="jsClientNav" style="display:none;">
        
            <? $clientNav = $this->navigation()->findAllBy('class', 'clientNav') ?>
            <?= $this->navigation()->menu()
                                   ->setPrefixForId('')
                                   ->setUlClass('cssUserNav')
                                   ->setRenderInvisible(true)
                                   ->renderMenu(new Zend_Navigation($clientNav)) ?>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        colorBoxSettings = {
             innerHeight:"50%",
             maxWidth:'100%'
        };

        $('#jsColorboxShort').colorbox(colorBoxSettings);

        $(document).bind('cbox_open', function(){
            $('.jsUserInfoButton').qtip('hide');
            resetTooltips();
        });

        $(document).bind('cbox_cleanup', function(){
            $('.jsUserInfoButton').qtip('hide');
            resetTooltips();
        });
   
        $('.jsUserInfoButton').qtip({
            content: $('.jsClientNav').html(),
            position: {
                adjust: {
                        x: -4,
                        y: 3
                    },
                corner: {
                    target: 'bottomRight',
                    tooltip: 'topRight'
                }
            },
            style: {
                width: 225,
                padding: 0,
                background: '#fff',
                color: '#fff',
                textAlign: 'left',
                border: {
                    width: 2,
                    radius:5,
                    color:'#fff'
                }
            },
            show: 'click',
            hide: 'click',
            api: {
                onShow: function() {
                    $('ul.cssUserInfo li').last().addClass('active');
                },
                onHide: function() {
                    $('ul.cssUserInfo li').last().removeClass('active');
                },
                onRender: function(){
                    $('#jsColorboxProfile, #jsColorboxProfileAccess').colorbox(colorBoxSettings);
                }
            }
        });
    });
</script>
