<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid ">
            <form class="cssUserImage span2"  id="jsAvatarUpload" enctype="multipart/form-data" method="post">
                <a href="#" title="<?= $this->translate('change profile image') ?>">
                <? if ($this->html('avatar') != ''): ?>
                    <img class="img-polaroid" name="avatar" src="<?= $this->html('avatar')?>" alt="<?= $this->translate('avatar') ?>">
                <? else: ?>
                    <img class="img-polaroid" name="avatar" src="<?= $this->baseUrl() ?>/img/dummy_user_200.png" alt="<?= $this->translate('avatar') ?>">
                <? endif; ?>
                </a>
                <?= $this->formAvatar->avatar; ?>
            </form>

            <form  class="span10" action="<?= $this->url(array(), 'addClient') ?>" method="post" id="jsClientForm">
                <dl class="row-fluid">
                    <dt class="span3">
                        <label id="addcompany"><?= $this->translate('company *') ?></label>
                    </dt>
                    <dd class="span9"><?= $this->form->company ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                        <label id="addprename"><?= $this->translate('prename *') ?></label>
                    </dt>
                    <dd class="span9"><?= $this->form->prename ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                        <label id="addsurname">
                            <?= $this->translate('surname *') ?>
                        </label>
                    </dt>
                    <dd class="span9"><?= $this->form->surname ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                        <label id="addstreet">
                            <?= $this->translate('street *') ?>
                        </label>
                    </dt>
                    <dd class="span9"><?= $this->form->street ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label id="addhousenumber">
                        <?= $this->translate('no. *') ?>
                    </label>
                    </dt>
                    <dd class="span9"><?= $this->form->houseNumber ?></dd>
                </dl>				
                <dl class="row-fluid">
                    <dt class="span3">
                    <label id="addpostcode">
                        <?= $this->translate('postcode *') ?>
                    </label>
                    </dt>
                    <dd class="span9"><?= $this->form->postcode ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label id="addcity">
                        <?= $this->translate('city *') ?>
                    </label>
                    </dt>
                    <dd class="span9"><?= $this->form->city ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label id="addphone">
                        <?= $this->translate('phone *') ?>
                    </label>
                    </dt>
                    <dd class="span9"><?= $this->form->phone ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label id="addfax">
                        <?= $this->translate('fax *') ?>
                    </label>
                    </dt>
                    <dd class="span9"><?= $this->form->fax ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label id="addemail">
                        <?= $this->translate('E-mail address *') ?>
                    </label>
                    </dt>
                    <dd class="span9"><?= $this->form->email ?></dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label id="addstatus">
                        <?= $this->translate('the client is') ?>
                    </label>
                    </dt>
                    <dd class="span9"><?= $this->form->status ?></dd>
                </dl>
                <h6>
                    <?= $this->translate('access data') ?>
                </h6>
                <dl class="row-fluid">
                    <dt class="span3">
                        <label id="addusername">
                            <?= $this->translate('username *') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->username ?>
                    </dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                        <label id="addpassword">
                            <?= $this->translate('password *') ?>
                        </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->password ?>
                    </dd>
                </dl>

                <? if ($this->html('avatar') != ''): ?>
                   <input id="tempAvatar" name="avatar_tmp" type="hidden" value="<?= $this->html('avatar') ?>" />
                <? endif; ?>
                <div class="row-fluid">
                    <input id="jsCancelButton" class="btn btn-info jsButton" type="reset" value="<?= $this->translate('cancel') ?>" />
                    <input class="btn btn-info jsButton" type="submit" value="<?= $this->translate('save') ?>" />
                </div>
            </form>
        </div>
    </div>
</div>

<?= $this->render('shared/passwordStrength.phtml'); ?>

<script type="text/javascript">
    $(document).ready(function() {
        $('#jsCancelButton').click(function() {
            location.href = '<?= $this->url(array(), 'clients'); ?>';
        });
    
        $("#password").focus(function(){
            $(this).click();
        });

        $("#jsClientForm").submit(function(event){
            $("[name]", $("#jsAvatarUpload")).each(function() {
                $("<input />", {
                    type:  "hidden",
                    name:  this.name,
                    value: this.value
                }).appendTo("#jsClientForm");
            });

            return true;
        });

        $('.cssUserImage a').click(function(){
            resetTooltips();
            $('.jsUserAvatar[type=file]').click();
            return false;
        });

        $('.jsUserAvatar').change(function(){
            $("#jsAvatarUpload").submit();
        });

        $("#jsAvatarUpload").ajaxForm({
            url: '<?= $this->url(array(), 'addClient') ?>?format=json',
            type: this.method,
            success: function(data){
                if ($("#tempAvatar").length === 0){
                    $("<input />", {
                        id: "tempAvatar",
                        name: "avatar_tmp",
                        type: "hidden"
                    }).appendTo("#jsClientForm");
                }
                if (typeof data === "string") data = eval('(' + data + ')');
                if (data.avatar && data.avatar !== null){
                    $(".cssUserImage img[name=avatar]").attr("src", data.avatar);
                    $("#tempAvatar").val(data.avatar);
                }else if (!$.isEmptyObject(data.formErrors) && !$.isEmptyObject(data.formErrors.avatar)){
                    setErrorTooltip(data.formErrors.avatar, "#jsClientForm .cssUserImage");
                }
                
                setMessages(data);
            },
            beforeSubmit: function(arr, $form, options) {
                $.each(arr, function(index, element){
                    if (element.type === "file" && element.value === ""){
                        arr[index] = [];
                    }
                });
            },
            complete: function() {
               if ($.browser.msie) $("#jsAvatarUpload")[0].reset();
            }
        });

        setPasswordStrength("#password");

        if ($.browser.msie){
            $("#avatar").show().css({
                borderColor: "transparent",
                borderStyle: "solid",
                borderWidth: "35px 0 0",
                width : $(".cssUserImage a").width(),
                height: $(".cssUserImage a").height()
            }).offset($('.cssUserImage a').offset());
            $('.cssUserImage a').unbind("click");
        }

    });
</script>