<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid text-left cssBoxCenter">
            <a href="<?= $this->url(array($this->html("client/_id"), $this->html("client/label")), "deleteClient"); ?>"
               class="jsIconDeleteTxt btn" title="<?= $this->translate("delete"); ?>">
                <i class="icon-trash"></i> <?= $this->translate("delete"); ?>
            </a>
            <a <?= $this->toBool("client/status") ? "style=\"display:none;\"" : null; ?>
                href="<?= $this->url(array($this->html("client/_id"), $this->html("client/label")), "changeClientState") ?>"
                class="jsIconStateTxt btn inactive" title="<?= $this->translate('activate'); ?>">
                <i class="icon-minus-sign"></i>
                <?= $this->translate("activate"); ?>
            </a>
            <a <?= !$this->toBool("client/status") ? "style=\"display:none;\"" : null; ?>
                href="<?= $this->url(array($this->html("client/_id"), $this->html("client/label")), "changeClientState"); ?>"
                class="jsIconStateTxt btn" title="<?= $this->translate('deactivate'); ?>">
                <i class="icon-ok-sign"></i>
                <?= $this->translate("deactivate"); ?>
            </a>
            <a href="<?= $this->url(array(), 'switchToClient') ?>?clientId=<?= $this->html("clientId") ?>"
                title="<?= $this->translate('login as') ?> <?= $this->html("client/label"); ?>"class="btn">
                <span><?= $this->translate('login as')?> <?= $this->html("client/label"); ?></span>
            </a>
        </div>
        <div class="row-fluid text-right cssStatusText cssBigItem">
            <span <?= !$this->toBool("client/status") ? "style=\"display:none;\"" : null; ?>
                class="span11 jsClientStatus stat online">
                online
            </span>
            <span <?= $this->toBool("client/status") ? "style=\"display:none;\"" : null; ?>
                class="span11 jsClientStatus stat offline">
                offline
            </span>
        </div>
        <div class="row-fluid cssBoxCenter jsConfigClient">
            <div class="span10">
                <div class="row-fluid">
                    <form class="cssUserImage span2" id="jsAvatarUpload" enctype="multipart/form-data" method="post">
                        <a href="#" title="<?= $this->translate('change profile image') ?>">
                            <? if ($this->html('client/avatar') != ''): ?>
                                <img class="img-polaroid" name="avatar" src="<?= $this->url(array($this->html("clientId")), "avatar"); ?>" alt="<?= $this->translate('avatar') ?>">
                            <? else: ?>
                                <img class="img-polaroid" name="avatar" src="<?= $this->baseUrl() ?>/img/dummy_user_200.png" alt="<?= $this->translate('avatar') ?>">
                            <? endif; ?>
                        </a>
                        <?= $this->form->avatar; ?>
                    </form>
                    <div class="span6 offset1">
                        <? if ($this->client->html('company') != ''): ?>
                            <dl class="row-fluid cssBigItem">
                                <?= $this->form->company; ?>
                            </dl>
                            <div class="row-fluid">
                                <dl class="pull-left cssItemWithoutLabel">
                                    <?= $this->form->prename ?>
                                </dl>
                                <dl class="pull-left cssItemWithoutLabel">
                                    <?= $this->form->surname ?>
                                </dl>
                            </div>
                        <? else: ?>
                            <dl class="row-fluid">
                                <?= $this->form->company; ?>
                            </dl>
                            <div class="row-fluid">
                                <dl class="cssBigItem pull-left cssItemWithoutLabel">
                                    <?= $this->form->prename; ?>
                                </dl>
                                <dl class="cssBigItem pull-left cssItemWithoutLabel">
                                    <?= $this->form->surname; ?>
                                </dl>
                            </div>
                        <? endif; ?>
                        <div class="row-fluid">
                            <dl class="pull-left cssItemWithoutLabel">
                                <?= $this->form->street ?>
                            </dl>
                            <dl class="pull-left cssItemWithoutLabel">
                                <?= $this->form->houseNumber ?>
                            </dl>
                        </div>
                        <div class="row-fluid">
                            <dl class="pull-left cssItemWithoutLabel">
                                <?= $this->form->postcode ?>
                            </dl>
                            <dl class="pull-left cssItemWithoutLabel">
                                <?= $this->form->city ?>
                            </dl>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <dl class="row-fluid">
                        <dt class="span3">
                        <label id="phone"><?= $this->translate('phone') ?></label>
                        </dt>
                        <dd class="span5 cssEditable">
                            <?= $this->form->phone ?>
                        </dd>
                    </dl>
                </div>
                <div class="row-fluid">
                    <dl class="row-fluid">
                        <dt class="span3">
                        <label id="fax"><?= $this->translate('fax') ?></label>
                        </dt>
                        <dd class="span5">
                            <?= $this->form->fax ?>
                        </dd>
                    </dl>
                </div>
                <div class="row-fluid">
                    <dl class="row-fluid">
                        <dt class="span3">
                        <label id="emailadress"><?= $this->translate('E-mail address:') ?></label>
                        </dt>
                        <dd class="span5">
                            <?= $this->form->email ?>
                        </dd>
                    </dl>
                </div>
                <?= $this->render('shared/additionalFields.phtml'); ?>
            </div>
        </div>
        <div class="row-fluid cssBoxCenter">
            <div class="span12">
                <ul class="nav nav-tabs unstyled" id="tabsClient">
                    <li id="tabTitleClientServices" class="active">
                        <a data-toggle="tab" href="#tabClientServices">
                            <?= $this->translate("Services"); ?> (<span class="jsTabServiceCount"><?= count($this->html('services')) ?></span>)
                        </a>
                    </li>
                    <li id="tabTitleClientNodes">
                        <a data-toggle="tab" href="#tabClientNodes">
                            <?= $this->translate("Nodes"); ?> (<span class="jsTabNodeCount"><?= count($this->nodes) ?></span>)
                        </a>
                    </li>
                    <li id="tabTitleClientDomains">
                        <a data-toggle="tab" href="#tabClientDomains">
                            <?= $this->translate("Domains"); ?> (<span class="jsTabDomainCount"><?= count($this->domains) ?></span>)
                        </a>
                    </li>
                    <li id="tabTitleClientAccess">
                        <a data-toggle="tab" href="#tabClientAccess">
                            <?= $this->translate("access data"); ?>
                        </a>
                    </li>
                    <li id="tabTitleClientLogs">
                        <a data-toggle="tab" href="#tabClientLogs">
                            <?= $this->translate("log"); ?>
                        </a>
                    </li>
                </ul>
                <div class="tab-content cssTabContentOuter row-fluid">
                    <div class="active tab-pane" id="tabClientServices">
                        <?= $this->render('clients/tabs/services.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabClientNodes">
                        <?= $this->render('clients/tabs/nodes.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabClientDomains">
                        <?= $this->render('clients/tabs/domains.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabClientAccess">
                        <?= $this->render('clients/tabs/access.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabClientLogs">
                        <?= $this->render('clients/tabs/logs.phtml'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="jsConfirmDeleteClient" class="modal hide fade">
    <div class="modal-body">
        <p><?= $this->translate('Shall the client really be deleted?') ?></p>
    </div>
    <div class="modal-footer">
        <a class="btn jsButtonCancel" data-dismiss="modal"><?= $this->translate('cancel') ?></a>
        <a class="btn btn-primary jsButtonDelete" data-dismiss="modal"><?= $this->translate('ok') ?></a>
    </div>
</div>
<?= $this->render('shared/passwordStrength.phtml'); ?>

<script type="text/javascript">
    $(document).ready(function() {
        $('.selectpicker').selectpicker();
        
        $('.jsConfigClient .jsEditable, #tabContentClientAccess .jsEditable').mazeEditable('<?= $this->url(array(), 'clientDetail') ?>?format=json', $.extend({
                onedit: function(data) {
                    $(".jsChangePassword:visible").find(".jsPasswordCancel").click();
                    $(".jsAdditionalControls:visible").find(".jsAdditionalCancel").click();
                }
            }, mazeEditableOptions)
        );

        $(".jsPasswordTrigger, .jsPasswordCancel").click(function(event){
            if (event.timeStamp === 0) return false;
            $("[type='password']").attr("disabled", false);
            $(".jsPasswordContainer").keypress(function(event){
                if (event.keyCode === 13 || event.which === 13){
                    event.preventDefault();
                }
            }).toggle();
            return false;
        }).filter(".jsPasswordCancel").click(function(event){
            if (event.timeStamp === 0) return false;
            $("#password, #confirmPassword").val(null).attr("disabled", true);
            resetTooltips();
        });
        
        $('.cssUserImage > a').click(function(){
            if ($(".jsChangePassword").is(":visible"))
                $(".jsPasswordCancel").click();
            resetTooltips();
            $('.jsUserAvatar[type=file]').click();
            return false;
        });
        $('.jsUserAvatar').change(function(){
            $("#jsAvatarUpload").submit();
        });

        $(".jsEditable").click(function(){
            if ($('.jsPasswordFields').is(':visible')){
                $('.jsTogglePassword').click();
            }
        });

        $("#jsClientForm").submit(function(){
            $("[type='password']").popover("destroy");
            $.ajax({
                url:  this.action+ "?format=json",
                type: this.method,
                data: $(this).serializeArray(),
                success: function(data){
                    if (data.result){
                        data.successes.push("<?= $this->translate('The password has been changed') ?>");
                        setTimeout(function(){
                            if ($(".jsChangePassword").is(":visible"))
                                $(".jsPasswordCancel").click();
                            resetTooltips();
                        }, 4000);
                    }

                    setTooltips(data, "#password");
                }
            });
            
            return false;
        }).keyup(function(event){
            if (event.keyCode === 13 || event.which === 13){
                $(this).submit();
            }
        });

        $("#jsAvatarUpload").ajaxForm({            
            url: "<?= $this->url(array(), 'clientDetail') ?>?format=json",
            type: this.method,
            success: function(data) {
                if (typeof data === "string") data = eval('(' + data + ')');
                if (!$.isEmptyObject(data.formErrors) && !$.isEmptyObject(data.formErrors.avatar)){
                    setErrorTooltip(data.formErrors.avatar, "#jsAvatarUpload");
                } else if (!$.isEmptyObject(data.client) && data.client.avatar){
                    image = '<?= $this->url(array($this->clientId), "avatar"); ?>';
                    $("#jsAvatarUpload img[name=avatar]").attr('src', image +'?'+new Date().getTime());
                }
                
                setMessages(data);
            },
            beforeSubmit: function(arr, $form, options) {
                $.each(arr, function(index, element){
                    if (element.type === "file" && element.value === ""){
                        arr[index] = [];
                    }
                });
            }
        });

        $(".jsIconStateTxt").click(function(){
            resetMessages();
            self = $(this);
            if (self.prop("disabled")){
                return false;
            }
            self.prop("disabled", true);
            $.ajax({
                url: this.href,
                data: {format: "json"},
                success:function(data){
                    if (!$.isEmptyObject(data.client) && self.hasClass("inactive") === data.client.status){
                        $(".jsIconStateTxt").toggle();
                        $(".jsClientStatus").toggle();
                    }
                    setMessages(data);
                },
                complete:function(){
                    self.prop("disabled", false);
                }
            });
            return false;
        });

        $(".jsIconDeleteTxt").live('click', function() {
            var self = $(this);
            var dialog = $("#jsConfirmDeleteClient").modal({backdrop:"static", show:true});
            dialog.find(".jsButtonDelete").unbind("click").click(function(){
                $.ajax({
                   url: self.attr("href"),
                   data: {format: "json"},
                   success:function(data){
                       if (data.status === true){
                           location.href = "<?= $this->url(array(), "clients") ?>";
                       }
                       setMessages(data);
                   }
                });
                dialog.modal("hide");
            }).andSelf().find(".jsButtonCancel").click(function(){
                dialog.modal("hide");
            });
            return false;
        });

        setPasswordStrength("#password", {placement: "left"});
        mazeEditableFields("<?= $this->url(array($this->html('client/_id'), $this->html('client/label')), 'addAdditionalFieldClient') ?>?format=json","<?= $this->url(array(), 'clientDetail') ?>?format=json");

        if ($.browser.msie){
            $("#avatar").show().css({
                borderColor: "transparent",
                borderStyle: "solid",
                borderWidth: "35px 0 0",
                width : $(".cssUserImage a").width(),
                height: $(".cssUserImage a").height()
            }).offset($('.cssUserImage a').offset());
            $('.cssUserImage a').unbind("click");
        }

    });
</script>
