<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid ">
            <div class="span12 ">
                <div class="span12">
                    <a class="btn btn-info jsButton" href="<?= $this->url(array(), 'addClient') ?>">
                        <?= $this->translate('Create client') ?>
                    </a>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div id="listClient" class="span12 jsListClient">
                <?= $this->render('shared/pager.phtml') ?>
                
                <div class="row-fluid cssColumn4">
                <? $columnCounter = 0; ?>    
                <? foreach ($this->raw('pager/data') as $id => $client): ?>

                    <div class="cssListColumn4 span3">
                        <div class="cssListColumn4Content" pagerindex="<?= $client->html('pagerIndex') ?>">
                            <div class="row-fluid">
                                <a class="span3" 
                                   title="<?= $client->html('label'); ?> <?= $this->translate('edit') ?>"
                                   href="<?= $this->url(array($client->html('_id'), $client->html('label')), 'clientDetail')?>">
                                    <? if($client->html('avatar') != ''): ?>
                                            <img src="<?= $this->urlAvatar($id, 120); ?>" 
                                                 class="img-rounded cssAvatar"
                                                 alt="<?= $this->translate('avatar') ?>"/>
                                        <? else: ?>
                                            <img src="<?= $this->baseUrl() ?>/img/dummy_user_200.png" 
                                                 class="img-rounded cssAvatar"
                                                 alt="<?= $this->translate('avatar') ?>"/>
                                        <? endif; ?>
                                </a>
                                <a href="<?= $this->url(array($client->html('_id'), $client->html('label')), 'clientDetail') ?>" 
                                   title="<?= $client->html('label'); ?> <?= $this->translate('edit') ?>"
                                   class="span9">
                                    <span class="pull-left cssUserItemSpan">
                                        <?= $client->html('label'); ?>
                                    </span>
                                </a>
                                <? if ($client->toBool("company")): ?>
                                <small class="span9 muted"><?= $this->translate('company') ?> <?= $client->html('company') ?></small>
                                <? endif; ?>
                                <small class="span9 muted"><?= $this->translate('status') ?> <?= $client->toBool("status")? $this->translate('activated') : $this->translate('deactivated');?></small>
                                <? if (!$client->toBool("company")): ?><small class="span9"></small><? endif; ?>
                                <div class="pull-right">
                                    <a href="<?= $this->url(array(), 'switchToClient') ?>?clientId=<?= $id ?>" 
                                       title="<?= $this->translate('login as') ?> <?= $client->html('label'); ?>"
                                       class="btn  pull-right">
                                        <span><?= $this->translate('log on') ?></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <? if(++$columnCounter==4): ?>
                        <? $columnCounter = 0; ?> 
                            </div>
                            <div class="row-fluid cssColumn4">
                    <? endif; ?>
                <? endforeach; ?>    
                </div>
            </div>
        </div>
    </div>     
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#coreSearchCategorySelected').html($('#coreSearchCategoryClients').html());
        $('#coreSearchCategoryList a').removeAttr('checked');
        $('#coreSearchCategoryClients').attr('checked', 'checked');

        $('#coreSearchInput').mazeSearch('option', 'source', '<?= $this->url(array(), 'clients') ?>?format=html');
        $('#coreSearchInput').mazeSearch('option', 'page', '<?= $this->html('pager/page') ?>');
    });
</script>
