<div>
    <h1 class="row-fluid cssBoxCenter">
      <?= $this->translate('An error occurred') ?>
    </h1>

    <h2 class="row-fluid cssBoxCenter">
        <?= $this->html("message") ?>
    </h2>

    <? if ($this->html("exceptionMessage") != ""): ?>
    <h3 class="row-fluid cssBoxCenter">
      <?= $this->translate('Exception information:') ?>
    </h3>

    <p>
        <b>
            <?= $this->translate('Message') ?>:
        </b>
        <?= $this->html("exceptionMessage") ?>
    </p>

    <h3 class="row-fluid cssBoxCenter">
        <?= $this->translate('Stack  trace:') ?>
    </h3>

    <pre><?= $this->html("exceptionTrace")  ?></pre>

    <h3 class="row-fluid cssBoxCenter">
        <?= $this->translate('Request Parameters:') ?>
    </h3>

    <pre><?= $this->html("requestParams") ?></pre>
    <? endif; ?>
</div>