<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?= $this->translate('Zend Framework Default Application') ?></title>
</head>
<body>
    <h1>
      <?= $this->translate('An error occurred') ?>
    </h1>
    <h2>
        <?= $this->html("message") ?>
    </h2>
    
    <? if ($this->html("exceptionMessage") != ""): ?>
    <h3>
      <?= $this->translate('Exception information:') ?>
    </h3>
    <p>
        <b>
            <?= $this->translate('Message') ?>:
        </b>
        <?= $this->html("exceptionMessage") ?>
    </p>
    <h3>
        <?= $this->translate('Stack  trace:') ?>
    </h3>
    <pre><?= $this->html("exceptionTrace")  ?></pre>

    <h3>
        <?= $this->translate('Request Parameters:') ?>
    </h3>
    <pre><?= $this->html("requestParams") ?></pre>
    <? endif; ?>

</body>
</html>
