<div class="row-fluid cssListing">
    <ul id="installedModules" class="span12 unstyled">
        <li class="row-fluid cssAction">
            <div class="offset10 span2 cssAction"></div>
        </li>
        <? foreach($this->installedModules as $id => $module): ?>
        <li class="cssListRow row-fluid jsModuleEntry">
            <div class="span10">
                <a class="cssListItem cssEllipsis span12" title="<?= $this->translate('detail') ?>"
                    href="#/modules/detail/<?= $module->html('name');?>">
                    <span class="cssAvatar">
                        <img src="<?= $this->baseUrl() ?>/img/dummy_module_50.png"
                             alt="<?= $this->translate('avatar') ?>"/>
                    </span>
                    <span class="">
                        <?= $module->html('label'); ?>
                    </span>
                    <small class="muted">
                        <span class="badge"><?= $module->html('repository/version') ?></span>
                    </small>
                    <small class="cssModuleDescription muted">
                        <strong><?= $this->translate('description') ?></strong>
                        <?= $module->html('description') ?>
                    </small>
                </a>
            </div>
        </li>
        <? endforeach; ?>
    </ul>
</div>
