<ul id="tabModuleNodesList" class="unstyled jsLineColor cssTab">
    <? foreach ($this->html('nodes') as $nodeId => $node): ?>
        <li id="tabModuleNodesListEntry-<?= $nodeId ?>" class="row-fluid cssLine jsLine">
            <a href="<?= $this->url(array($node->html('name')), 'nodedetail') ?>"
               title="<?= $node->html('name') ?>" class="span8">
                <?= $node->html('name') ?>
            </a>
            <a href="#" class="pull-right jsDomainsOnNode">
                <?= $this->translate('Domains') ?> (<?= count($node->html('domains')) ?>)
            </a>
            
            <div class="jsUserNodeDomains" style="display:none;">
            <? if($node->toBool('domains')): ?>
                <ul id="tabModuleNodesListDomains-<?= $nodeId ?>" class="cssPopoverTabList unstyled pull-left">
                    <? foreach ($node->html('domains') as $domain): ?>
                        <li>
                            <a href="<?= $this->url(array($domain->html('name')), 'domaindetail') ?>"
                               title="<?= $domain->html('name') ?>" class="pull-left">
                                <span>
                                    <?= $domain->html('name') ?>
                                </span>
                            </a>
                        </li>
                    <? endforeach; ?>
                </ul>
            <? endif; ?>
            </div>
        </li>
    <? endforeach; ?>
</ul>
<script type="text/javascript">
    $(document).ready(function() {
        $('.jsDomainsOnNode').each(function() {
            var parentLi = $(this).closest('li');
            var content = $.trim($(parentLi).find('.jsUserNodeDomains').html());
            
            if(content) {
                $(this).popover({
                    placement: 'bottom',
                    content: content,
                    html: true,
                    trigger: 'click'
                });
            }
            
            $(this).click(function(){return false;});
        });
    });
</script>
