<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <div class="span10">
                <div class="row-fluid">
                    <div class="cssUserImage span2">
                        <img name="avatar" class="img-polaroid" id="jsImageNodeType" src="<?= $this->baseUrl() ?>/img/dummy_node_200.png" alt="<?= $this->translate('avatar') ?>" width="100px">
                    </div>
                    <div class="span9 offset1">
                        <div class="row-fluid cssBigItem">
                            <span>
                                <?= $this->translate('Attention') ?>
                                <?= $this->translate('a new or unregistered node was found') ?>
                            </span>
                        </div>
                        <div class="row-fluid">
                            <span>
                                <?= $this->translate('Report message') ?>
                            </span>
                            <div class="row-fluid">
                                <span>
                                    <?= $this->translate('A new or unregistered node would be connected with Maze dashboard.') ?>
                                </span>
                            </div>
                            <div class="row-fluid">
                                <span>
                                    <?= $this->translate('Please enter what is to happen!') ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <form class="jsRegisterApi"action="<?= $this->url(array($this->html('data/name')), 'registerApi') ?>" method="post">
                        <input name="remoteForm" type="hidden" value="1" />
                        <dl class="row-fluid">
                            <dt class="span3">
                                <label><?= $this->translate('node type') ?></label>
                            </dt>
                            <dd class="span5">
                                <?= $this->form->nodetype ?>
                            </dd>
                        </dl>
                        <dl class="row-fluid">
                            <dt class="span3">
                                <label><?= $this->translate('node name') ?></label>
                            </dt>
                            <dd class="span5">
                                <span><?= $this->html('data/name') ?></span>
                            </dd>
                        </dl>
                        <dl class="row-fluid">
                            <dt class="span3">
                                <label><?= $this->translate('ip address') ?></label>
                            </dt>
                            <dd class="span5">
                                <span><?= $this->html('data/ipAddress') ?></span>
                            </dd>
                        </dl>
                        <dl class="row-fluid" style="display:none;">
                            <?= $this->form->apiKey ?>    
                        </dl>
                        <div class="row-fluid">
                            <input class="btn btn-info" type="submit" value="<?= $this->translate('Connecting with Maze.dashboard') ?>" />
                            <input class="btn btn-info" type="reset" onclick="location = '<?= $this->url(array(), "nodes"); ?>'" value="<?= $this->translate('cancel') ?>" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $("#nodetype.selectpicker").selectpicker();
        $("select#nodetype").val(function(){
            index = this.options.selectedIndex;
            value = this.options.item(index).value;
            this.nodetype = {
                default   : "dummy_node_200.png",
                virtual   : "dummy_vm_200.png",
                cloud     : "dummy_cloud_200.png",
                dedicated : "dummy_server_200.png"
            };
            this.setNodetype = function( type ){
                if (typeof this.nodetype[type] === "undefined")
                    type = "default";
                $("#jsImageNodeType").attr("src", "<?= $this->baseUrl() ?>/img/" +this.nodetype[type]);
                return type;
            };
            return this.setNodetype(value);
        }).change(function(event){
            event.target.setNodetype(event.target.value);
        });
    });
</script>