<div class="row-fluid">
    <div class="span12" ng-controller="ModuleController">
        <? if ($this->toBool("module/installed") == true): ?>
        <div class="row-fluid text-left cssBoxCenter">
            <a href="<?= $this->url(array($this->html('module/name')), 'moduleDeinstall'); ?>" id="jsUninstallModule"
               class="jsIconDeleteTxt btn" title="<?= $this->translate("delete module"); ?>">
                <i class="icon-trash"></i> <?= $this->translate("uninstall"); ?>
            </a>
        </div>
        <? endif; ?>
        <div class="row-fluid cssBoxCenter">
            <div class="span10">
                <div class="row-fluid">
                    <div class="cssUserImage span2">
                        <img name="avatar" class="img-polaroid" src="<?= $this->baseUrl() ?>/img/dummy_module_200.png" alt="<?= $this->translate('avatar') ?>">
                    </div>
                    <div class="span9 offset1">
                        <dl class="row-fluid cssBigItem">
                            <span class="span9">
                                <span><?= $this->html('module/label') ?></span>
                            </span>
                        </dl>
                        <dl class="row-fluid">
                            <dt class="span3">
                                <label>
                                    <?= $this->translate('vendor'); ?>
                                </label>
                            </dt>
                            <dd class="span9">
                                <span>
                                    <?= $this->html('module/vendor'); ?>
                                </span>
                            </dd>
                        </dl>
                        <dl class="row-fluid">
                            <dt class="span3">
                                <label>
                                    <?= $this->translate('Version'); ?>
                                </label>
                            </dt>
                            <dd class="span9">
                                <span>
                                    <?= $this->html('module/repository/version'); ?>
                                </span>
                            </dd>
                        </dl>
                    </div>
                </div>
                <div class="row-fluid">
                    <dl class="row-fluid">
                        <dt class="span3">
                            <label>
                                <?= $this->translate('description') ?>
                            </label>
                        </dt>
                        <dd class="span9">
                            <span>
                                <?= $this->translate((string) $this->html('module/description')) ?>
                            </span>
                        </dd>
                    </dl>
                    <dl class="row-fluid">
                        <dt class="span3">
                            <label>
                                <?= $this->translate('authors'); ?>
                            </label>
                        </dt>
                        <dd class="span9">
                            <? foreach ($this->html('module/authors') as $index => $author): ?>
                                <div>
                                <?= $author->html("name"); ?>
                                <? if ($author->html("email") != ""): ?>
                                     - <i><?= $author->html("email"); ?></i>
                                <? endif; ?>
                                </div>
                            <? endforeach; ?>
                        </dd>
                    </dl>
                    <dl class="row-fluid">
                        <dt class="span3">
                            <label>
                                <?= $this->translate('Wiki') ?>
                            </label>
                        </dt>
                        <dd class="span9">
                            <span>
                                <a href="<?= $this->html('module/wiki'); ?>">
                                    <?= $this->html('module/wiki'); ?>
                                </a>
                            </span>
                        </dd>
                    </dl>
                </div>

                <div class="row-fluid cssAdditionalFields" id="additionalFieldsContent">
                    <div maze-additional fields="module.additionalFields" update="update($data)"></div>
                </div>
            </div>
        </div>
        <div class="row-fluid cssBoxCenter">
            <? if ($this->toBool("module/installed") == true): ?>
            <div class="span12">
                <ul class="nav nav-tabs unstyled" id="tabsModule">
                    <li id="tabTitleModuleConfig" class="active">
                        <a data-toggle="tab" href="#tabModuleConfig">
                            <?= $this->translate("Configuration"); ?>
                        </a>
                    </li>
                    <li id="tabTitleModuleNodes">
                        <a data-toggle="tab" href="#tabModuleNodes">
                            <?= $this->translate("Nodes"); ?>  (<span class="jsTabNodeCount"><?= count($this->nodes) ?></span>)
                        </a>
                    </li>
                    <li id="tabTitleModuleDomains">
                        <a data-toggle="tab" href="#tabModuleDomains">
                            <?= $this->translate("Domains"); ?>  (<span class="jsTabDomainCount"><?= count($this->domains) ?></span>)
                        </a>
                    </li>
                    <li id="tabTitleModuleLogs">
                        <a data-toggle="tab" href="#tabModuleLogs">
                            <?= $this->translate("log"); ?>
                        </a>
                    </li>
                </ul>
                <div class="tab-content cssTabContentOuter row-fluid">
                    <div id='loadingIndicator' style='display:none;'>
                        <img src="<?= $this->baseUrl() ?>/img/js/loading.gif">
                    </div>
                    <div class="active tab-pane cssTabContentAll" id="tabModuleConfig">
                        <? if($this->toBool('config/routes/config/config/route')): ?>
                            <div ng-include="'<?= $this->url(array(), (string) $this->html('config/routes/config/config/route')); ?>'"></div>
                        <? else: ?>
                            <?= $this->translate('No configuration available'); ?>
                        <? endif; ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabModuleNodes">
                        <?= $this->render('modules/tabs/nodes.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabModuleDomains">
                        <?= $this->render('modules/tabs/domains.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabModuleLogs">
                        <?= $this->render('modules/tabs/logs.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="jsLogsClient">
                        <?= $this->render('modules/tabs/logs.phtml') ?>
                    </div>
                </div>
            </div>
            <? endif; ?>
        </div>
    </div>
    <div id="jsConfirmDeleteModule" class="modal hide fade">
        <div class="modal-body">
            <p><?= $this->translate('Shall the module really be removed?'); ?></p>
            <p style="display:none;">
                <img src="/img/js/loading.gif" style="margin:-7px 0;position:relative;right:6px;"><?= $this->html('module/label') ?> ...<?= $this->translate("uninstall"); ?>
            </p>
        </div>
        <div class="modal-footer">
            <a class="btn jsButtonCancel" data-dismiss="modal"><?= $this->translate('cancel') ?></a>
            <a class="btn btn-primary jsButtonDelete"><?= $this->translate('ok') ?></a>
        </div>
    </div>
</div>
<script type="text/javascript">
    var app = angular.module('maze');

    app.controller('ModuleController', ['$scope', 'modulesService', function($scope, modulesService){
        $scope.module = {name: "<?= $this->html("module/name"); ?>"};

        $scope.update = function(data){
            return modulesService.set($scope.module.name, data).success(function(module, status){
                if (status === 202) {
                    $scope.module = module;
                }
            });
        };

        modulesService.get($scope.module.name).success(function(module){
            $scope.module = module;
        });
    }]);

    $(document).ready(function() {
        initTabClickEvent();
        $('a[data-toggle="tab"]:visible:first').click();

        $("#jsUninstallModule").click(function(e) {
            e.preventDefault();
            var self = this;
            var dialog = $("#jsConfirmDeleteModule").modal({backdrop:"static", show:true});
                dialog.find(".jsButtonDelete").unbind("click").click(function(){
                    dialog.find(".modal-body p").toggle().andSelf().find(".modal-footer").toggle();
                $.ajax({
                    url: $(self).attr("href"),
                    data: {format: "json"},
                    success:function(data){
                        if (data.result === true){
                            location.href = "<?= $this->url(array(), "modules") ?>";
                        }
                        setMessages(data, true);
                    },
                    complete:function(){
                        $(self).attr("disabled", false);
                        dialog.modal("hide").find(".modal-footer").toggle()
                              .andSelf().find(".modal-body p").toggle();
                    }
                });
            }).andSelf().find(".jsButtonCancel").click(function(){
                $(self).attr("disabled", false);
            });
            $(self).attr("disabled", true);
            return false;
        });
    });

    function initTabClickEvent() {
        $('a[data-toggle="tab"]:visible').click(function (e) {
            e.preventDefault();
            var target = $($(this).attr('href'));
            if($(target).length > 0 && $(target).attr('href') && $(target).attr('loaded') !== "true") {
                $('#loadingIndicator').show();
                $(target).attr('loaded', true);

                $(target).load($(target).attr('href'), function(response, status) {
                    if (status === "error") {
                        var msg = "<?= $this->translate('Couldn\'t load module configuration') ?>";
                        $(target).html(msg);
                      }

                    $('#loadingIndicator').hide();
                });
            }
        });
    }
</script>
