<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid text-left cssBoxCenter">
            <button id="buttonListUpdate" title="<?= $this->translate('Update') ?>" class="btn">
                <span>
                    <? if($this->toBool('lastModuleSync')): ?>
                        <?= $this->translate('Update (%1$s)', $this->html('lastModuleSync')) ?>
                    <? else: ?>
                        <?= $this->translate('Update') ?>
                    <? endif; ?>
                </span>
            </button>
        </div>

        <ul class="nav nav-tabs" id="jsTabsModules">
            <li class="active">
                <a href="#/modules/#jsInstalledModule" data-toggle="tab"><?= $this->translate("Installed"); ?> (<?= count($this->installedModules) ?>)</a>
            </li>
            <li>
                <a href="#/modules/#jsAvailableModule" data-toggle="tab"><?= $this->translate("Available"); ?> (<?= count($this->availableModules) ?>)</a>
            </li>
            <li>
                <a href="#/modules/#jsUpdateModule" data-toggle="tab"><?= $this->translate("Latest Updates"); ?> (<?= count($this->updateableModules) ?>)</a>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="jsInstalledModule">
                <?= $this->render('modules/tabs/installedModules.phtml'); ?>
            </div>
            
            <div class="tab-pane" id="jsAvailableModule">
                <?= $this->render('modules/tabs/availableModules.phtml'); ?>
            </div>
            
            <div class="tab-pane" id="jsUpdateModule">
                <?= $this->render('modules/tabs/updateableModules.phtml'); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#jsTabsModules a").filter("[href='"+ location.hash +"']").click();

        $('#buttonListUpdate').click(function() {
            resetMessages();
            self = $(this);
            if (self.prop("disabled")){
                return false;
            }

            self.prop("disabled", true);
            $.ajax('<?= $this->url(array(), 'moduleSync') ?>?format=json', {
                type: 'POST',
                success: function(data) {
                    if(data.result === true) {
                        self.trigger("reloadTemplateCache");
                    }
                    setMessages(data);
                },
                error: function() {
                    setErrorMessages(['<?= $this->translate('Request failed') ?>']);
                },
                complete: function() {
                    self.prop("disabled", false);
                }
            });

            return false;
        });
    });
</script>
