<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
    <head>
        <link rel="icon" href="<?= $this->baseUrl() ?>/img/maze.ico" />
        <?= $this->headMeta()->appendHttpEquiv('expires', '604800') ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8"/>
        <? $this->headTitle()->setSeparator(' - '); ?>
        <?= $this->headTitle('Maze.dashboard', 'PREPEND') ?>
        <? $this->headLink()->prependStylesheet($this->baseUrl() . '/css/admin.css') ?>
        <? $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap-select.min.css') ?>
        <? $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap-responsive.css') ?>
        <? $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css') ?>
        <?= $this->headLink() ?>
        <? $this->headScript()->prependFile($this->baseUrl() . '/js/bootstrap.min.js') ?>
        <? $this->headScript()->prependFile($this->baseUrl() . '/js/min/jquery-1.8.2.min.js') ?>
        
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top ">
            <div class="navbar-inner cssHeader">
                <div class="container-fluid">
                    <div class="row-fluid cssHeaderInner">
                        <a class="brand" id="home"
                           href="<?= $this->url(array(), 'index') ?>" title="maze.dashboard">
                            <img src="<?= $this->baseUrl() ?>/img/logo_maze_sh.png"
                                 width="40px" height="40px"
                                 alt="<?= $this->translate('image') ?>" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="wrapper">
            <div class="proper-content">
                <div class="cssBreadcrumb">
                    <div class="container-fluid">
                        <div class="row-fluid cssBreadcrumbInner"></div>
                    </div>
                </div>
                <div class="cssContent">
                    <div id="mainContent" class="container-fluid">
                        <?= $this->render('admin/messages.phtml') ?>
                        <?php echo $this->layout()->content; ?>
                    </div>
                    <div class="push"></div>
                </div>
            </div>
        </div>
    </body>
</html>
