<div class="container_16">
    <div class="cssForm grid_16">
        <div class="cssContentLigthbox">
            <h1>
                <?= $this->translate('My profile') ?>
            </h1>
            <div class="cssDetailPadding30 cssForm grid_16">
                <div class="cssFormBoxLong grid_16">
                    <div class="cssWidth20Pr cssAvatar">
                        <form id="jsMyAvatarUpload" enctype="multipart/form-data" method="post">
                            <span href="#" class="cssUserImage">
                                <? if ($this->client->html('avatar') != ''): ?>
                                    <img name="avatar" src="<?= $this->url(array($this->client->html("_id")), "avatar"); ?>" alt="<?= $this->translate('avatar') ?>" />
                                <? else: ?>
                                    <img name="avatar" src="<?= $this->baseUrl() ?>/img/dummy_user_200.png"  alt="<?= $this->translate('avatar') ?>" />
                                <? endif; ?>
                                <a href="#" title="<?= $this->translate('change profile image') ?>">
                                    <?= $this->translate('change profile image') ?>
                                </a>
                                <?= $this->form->avatar; ?>
                            </span>
                        </form>
                    </div>
                    <div class="cssWidth80Pr">
                        <form enctype="multipart/form-data" id="jsMyProfileForm" action="" method="POST">
                        
                            <div class="grid_16">
                                <? if ($this->client->html('company') != ""): ?>
                                    <dl class="cssHideItem cssCompanyItem">
                                <? else: ?>
                                    <dl class="cssHideItem">
                                <? endif; ?>
                                        <?= $this->form->company ?>
                                    </dl>
                            </div>
                            <div class="grid_16">
                                <? if ($this->client->html('company') != ""): ?>
                                    <dl class="cssHideItem">
                                <? else: ?>
                                    <dl class="cssHideItem cssCompanyItem">
                                <? endif; ?>
                                        <?= $this->form->prename ?>
                                    </dl>
                                <? if ($this->client->html('company') != ""): ?>
                                    <dl class="cssHideItem">
                                <? else: ?>
                                    <dl class="cssHideItem cssCompanyItem">
                                <? endif; ?>
                                        <?= $this->form->surname ?>
                                    </dl>
                            </div>
                            <div class="grid_16">
                                <dl class=" cssHideItem">
                                    <?= $this->form->street ?>
                                </dl>
                                <dl class=" cssHideItem">
                                    <?= $this->form->houseNumber ?>
                                </dl>
                            </div>
                            <div class="grid_16">
                                <dl class="cssHideItem">
                                    <?= $this->form->postcode ?>
                                </dl>
                                <dl class="cssHideItem">
                                    <?= $this->form->city ?>
                                </dl>
                            </div>
                        </div>
                        <dl class="grid_16">
                            <?= $this->form->phone ?>
                        </dl>
                        <dl class="grid_16">
                            <?= $this->form->fax ?>
                        </dl>
                        <dl class="grid_16">
                            <?= $this->form->email ?>
                        </dl>
                        <dl class="grid_16">
                            <?= $this->form->username ?>
                        </dl>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('.jsEditable').mazeEditable('<?= $this->url(array(), 'profile') ?>?format=json');
        $('.jsButton').button();

    $("#jsMyAvatarUpload .cssUserImage a").click(function(){
        resetTooltips();
        $("#jsMyAvatarUpload").find(".jsUserAvatar[type=file]").click();
        return false;
    });
    $("#jsMyAvatarUpload .jsUserAvatar").change(function(){
        $("#jsMyAvatarUpload").submit();
    });

    $("#jsMyAvatarUpload").ajaxForm({
        url: "<?= $this->url(array(), 'profile') ?>?format=json",
        type: "post",
        success: function(data) {
            if (typeof data === "string")  data = eval('(' + data + ')');
            if (!$.isEmptyObject(data.formErrors) && !$.isEmptyObject(data.formErrors.avatar)){
                setErrorTooltip(data.formErrors.avatar, "#jsMyAvatarUpload .cssUserImage");
            } else if (!$.isEmptyObject(data.client) && data.client.avatar){
                image = '<?= $this->url(array($this->html("client/_id")), "avatar"); ?>';
                $("#jsMyAvatarUpload img[name=avatar], #jsAvatar").attr('src', image +'?'+new Date().getTime());
            }
        },
        beforeSubmit: function(arr, $form, options) {
            $.each(arr, function(index, element){
                if (element.type === "file" && element.value === ""){
                    arr[index] = [];
                }
            });
        }
    });

    $(document).bind("cbox_complete", function(){
        if ($.browser.msie){
            cbox = $("#cboxContent");
            cbox.find("#avatar").show().css({
                borderColor: "transparent",
                borderStyle: "solid",
                borderWidth: "35px 0 0",
                width : cbox.find(".cssUserImage a").width(),
                height: cbox.find(".cssUserImage a").height()
            }).offset(cbox.find(".cssUserImage a").offset());
            cbox.find(".cssUserImage a").unbind("click");
        }
    });

    });
</script>