<div class="cssLoginBox grid_16 cssForgotPasswort">
    
    <form method="post" action="<?= $this->url(array(), 'forgotPassword') ?>">
        <div class="cssLoginBoxHead">
            <img src="<?= $this->baseUrl() ?>/img/icon_questionmark.png"  alt="<?= $this->translate('image') ?>" />
            <h1>
                <?= $this->translate('forgot password?') ?>
            </h1>
            <a href="<?= $this->url(array(), 'login') ?>">
                <?= $this->translate('login') ?>
            </a>
        </div>
        <? if ($this->html('result') == '1'): ?>
            <p>
                <?= $this->translate('info password reset email sent') ?>
            </p>
        <? elseif (!$this->html('result')): ?>
            <div class="cssErrorMessage ui-widget">
                <div class="ui-state-error ui-corner-all">
                    <p>
                        <span class="ui-icon ui-icon-alert"></span>
                        <strong>
                            <?= $this->translate('Attention! Following errors occurred:') ?>
                        </strong>
                    </p>
                    <p>
                        <?= $this->translate('There is no user registered with that email address.') ?>
                    </p>
                </div>
            </div>
        <? endif; ?>

        <? if ($this->html('result') != '1'): ?>
            <p>
                <?= $this->translate('In order! Change your password in three easy steps. This will keep your new password protected.') ?>
            </p>
            <ul class="cssPasswordResetList">
                <li><?= $this->translate('Please enter below your email address') ?></li>
                <li><?= $this->translate('You will receive via email a temporary link') ?></li>
                <li><?= $this->translate('Use the link to change your password') ?></li>
            </ul>
            <dl>
                <?= $this->form->userEmail ?>
            </dl>
            <span>
                <?= $this->translate('Enter the email address that you used to log in Maze.dashboard. We will then send a link to this address') ?>
            </span>
            <div class="cssLoginButton">
                <input type="submit" class="jsButton" name="resend-password" value="<?= $this->translate('Request password') ?>"/>
            </div>
        <? endif; ?>
    </form>
</div>