<div class="cssLoginBox">
    <div class="cssLoginBoxHead">
        <h1>
            <?= $this->translate('initial registration') ?>
        </h1>
        
    </div>
    <form method="post" action="<?= $this->url(array(), 'requestPassword') ?>">
        <? if ($this->html('result') == '1'): ?>
            <p>
                <?= $this->translate('info password request email sent') ?>
            </p>
        <? elseif (!$this->html('result')): ?>
            <div class="cssErrorMessage ui-widget">
                <div class="ui-state-error ui-corner-all">
                    <p>
                        <span class="ui-icon ui-icon-alert"></span>
                        <strong>
                            <?= $this->translate('Attention! Following errors occurred:') ?>
                        </strong>
                    </p>
                    <p>
                        <?= $this->translate('There is no user registered with that email address.') ?>
                    </p>
                </div>
            </div>
        <? endif; ?>

        <? if ($this->html('result') != '1'): ?>
            <p>
                <?= $this->translate('Welcome to Maze.dashboard! Set your password in 3 easy steps. This will keep your password protected.') ?>
            </p>
            <ul class="cssPasswordResetList">
                <li><?= $this->translate('Please enter the email address (from email)') ?></li>
                <li><?= $this->translate('You will receive via email a temporary link') ?></li>
                <li><?= $this->translate('Use the link to create your password') ?></li>
            </ul>
            <dl>
                <?= $this->form->userEmail ?>
            </dl>
            <span>
                <?= $this->translate('Enter the email address that we sent you in the mail. We will send a link to this address.') ?>
            </span>
            <div class="cssLoginButton">
                <input type="submit" class="jsButton" name="resend-password" value="<?= $this->translate('Request password') ?>"/>
            </div>
        <? endif; ?>
    </form>
</div>