<div class="cssLoginBox grid_16">
    
    <form action="<?= $this->url(array(), 'resetPassword'); ?>?token=<?= $this->token; ?>" method="post">
        <div class="cssLoginBoxHead">
            <img src="<?= $this->baseUrl() ?>/img/icon_login.png"  alt="<?= $this->translate('image') ?>" />
            <h1>
                <?= $this->translate('Set new password') ?>
            </h1>
        </div>
    <? if ($this->html('tokenValid') == '0'): ?>
        <p>
            <?= $this->translate('Sorry, the link to reset your password has already expired') ?>
        </p>
    <? else: ?>
        <? if ($this->html('result') === '-4'): ?>
            <div class="cssErrorMessage ui-widget">
                <div class="ui-state-error ui-corner-all">
                    <p>
                        <span class="ui-icon ui-icon-alert"></span>
                        <strong>
                            <?= $this->translate('Attention! Following errors occurred:') ?>
                        </strong>
                    </p>
                    <p>
                        <?= $this->translate('Send failed, this account is deactivated') ?>
                    </p>
                </div>
            </div>
        <? elseif ($this->html('result') == '0'): ?>
            <div class="cssErrorMessage ui-widget">
                <div class="ui-state-error ui-corner-all">
                    <p>
                        <span class="ui-icon ui-icon-alert">
                        </span>
                        <strong>
                            <?= $this->translate('Attention! Following errors occurred:') ?>
                        </strong>
                    </p>
                    <p>
                        <?= $this->translate('The password could not be reset') ?>
                    </p>
                </div>
            </div>
        <? elseif ($this->html('result') == '1'): ?>
        <p>Ihr neues Passwort wurde erfolgreich gespeichert. Klicken Sie den unten stehenden Link an, um sich in Maze.dashboard einzuloggen.</p>
        <a href="<?= $this->url(array(), 'index')?>" class="cssButtonForm jsButton">Zur Anmeldung</a>
        <? endif; ?>
        <? if ($this->html('tokenValid') == '1' && $this->html('result') != '1'): ?>
            <p>
                <?= $this->translate('Please enter your new password. Once you have saved the password, you will be redirected to login') ?>
            </p>
            <dl><?= $this->html('form/password') ?></dl>
            <dl><?= $this->html('form/confirmPassword') ?></dl>
            <div class="cssLoginButton">
                <input class="jsButton cssButtonForm" type="submit" value="<?= $this->translate('save') ?>" />
            </div>
        <? endIf; ?>
    <? endif; ?>
    </form>
</div>