<div id="clientServicesContent" class="row-fluid">

    <div class="row-fluid">
        <maze-dl-wrapper label="<?= $this->translate('Add new service') ?>" dl-class="span12" dt-class="span3 text-right"
                         dd-class="span7">
            <span ng-show="loadServices">
                <img src="<?= $this->baseUrl() ?>/img/js/loading.gif" title="<?= $this->translate('Loading...') ?>">
                <?= $this->translate('Loading...') ?>
            </span>

            <select ng-options="service.name as service.label for service in services.available"
                    ng-model="services.selected" ng-disabled="services.available.length <= 1" ng-show="!loadServices">
            </select>

            <button class="btn btn-info" ng-disabled="!services.selected" ng-show="!loadServices"
                    ng-click="addService(services.selected)">
                <?= $this->translate('ok') ?>
            </button>

            <div class="row-fluid" ng-show="errAddService.length">
                <alert ng-repeat="error in errAddService" type="'danger'">{{error}}</alert>
            </div>
        </maze-dl-wrapper>
    </div>

    <div class="row-fluid tabbable tabs-left cssTabContentAll">
        <ul id="tabServicesList" class="nav nav-list unstyled cssTabMenuLeft span3">
            <li ng-repeat="service in client.services" ng-class='{active:$first}'>
                <a class="link" data-toggle="tab" id="tabServices-{{service.name}}"
                   href="#tabServicesContent-{{service.name}}">
                    <i class="icon-chevron-right text-right"></i>
                    <i class="icon-trash text-right" ng-click="modalRemoveClientService(service)"></i>
                    <span>
                        {{service.label}}
                    <span>
                </a>
            </li>
        </ul>

        <div id="tabServiceContent" class="tab-content cssTabContent span9">
            <div ng-repeat="service in client.services" class="tab-pane" id="tabServicesContent-{{service.name}}" ng-class='{active:$first}'>

                <ng-include ng-if="service.configUrl" src="service.configUrl">
                    <img src="<?= $this->baseUrl() ?>/img/js/loading.gif" title="<?= $this->translate('Loading...') ?>">
                    <?= $this->translate('Loading...') ?>
                </ng-include>

                <div ng-if="!service.configUrl">
                    <?= $this->translate('No configuration available'); ?>
                </div>

            </div>
        </div>
    </div>

</div>

<script type="text/ng-template" id="modalRemoveClientService.html">
    <div class="modal-header">
        <h3 class="modal-title">Remove Service {{service.name}} from client {{client.label}}</h3>
    </div>
    <div class="modal-body">
        <p>
            Should the service {{service.name}} be removed from the client?
        </p>
        <alert ng-repeat="error in errMessages" type="'danger'">{{error}}</alert>
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger" ng-click="ok()">
            <?= $this->translate('OK') ?>
        </button>
        <button class="btn" ng-click="cancel()">
            <?= $this->translate('Cancel') ?>
        </button>
    </div>
</script>
