<div id="jsPassword" style="display:none;">
    <div class="cssPassword" id="jsPassword">
        <div class="jsPasswordTitle">
            <div class="cssPasswordTitle">
                <span>
                    <?= $this->translate('password strength') ?>:
                </span>
                <span class="jsPasswordDescription cssPasswordDescription">
                    <?= $this->translate('very weakly') ?>
                </span>
            </div>
            </div>

        <div class="jsPasswordStrengthBody">
            <div class="cssPasswordStrength" style="background:#f5f5f5;display:inline-block;width:100%;">
                <span class="jsPasswordStrength strength0"></span>
            </div>
            <span class="cssPasswordSupport">
                <?= $this->translate('Use at least 6 characters.') ?>
                <?= $this->translate('Use upper and lower case letters.') ?>
                <?= $this->translate('Include punctuation marks and / or numbers.') ?>
                <?= $this->translate('Include similar looking substitutions, such as the number zero for the letter O.') ?>
            </span>
        </div>
    </div>
</div>
<script type="text/javascript">

    /**
     * enables password strength tooltip on the target element(s)
     * 
     * @param   {String|Array} targets
     * @param   {Object} options (popover)
     * @returns {Void}
     */
    function setPasswordStrength(targets, options)
    {
        $(targets).each(function(index, target){
            if (typeof target.selector === "undefined"){
                target = $(target);
            }

            var targetElement = target;
            var tooltipOption = $.extend({
                html     : true,
                placement: "right",
                title    : $('#jsPassword .jsPasswordTitle').html(),
                content  : $('#jsPassword .jsPasswordStrengthBody').html()
            }, options);

            targetElement.keyup(function() {
                passwordTooltip = $(".jsPasswordStrength");
                if ($(this).hasClass("jsTooltip"))
                    $(this).removeClass("jsTooltip").popover("destroy");
                if (passwordTooltip.length >= 1 && passwordTooltip.eq(0).is(":hidden")){
                    targetElement.popover(tooltipOption).popover("show");
                }
                passwordStrength(this.value);
            }).keydown(function(event) {
                keyCode = (event.keyCode || event.which); 
                if (keyCode === 9){
                    targetElement.popover("destroy");
                }
            }).focusout(function(){
                targetElement.popover("destroy");
            });
        });
    }

    function passwordStrength(password)
    {
        var desc = new Array();
        desc[0] = "<?= $this->translate('very weakly') ?>";
        desc[1] = "<?= $this->translate('weak') ?>";
        desc[2] = "<?= $this->translate('better') ?>";
        desc[3] = "<?= $this->translate('medium') ?>";
        desc[4] = "<?= $this->translate('strong') ?>";
        desc[5] = "<?= $this->translate('very strong') ?>";

        var score   = 0;

        if (password.length === 0) return;

        //if password bigger than 6 give 1 point
        if (password.length > 6) score++;

        //if password has both lower and uppercase characters give 1 point	
        if ( ( password.match(/[a-z]/) ) && ( password.match(/[A-Z]/) ) ) score++;

        //if password has at least one number give 1 point
        if (password.match(/\d+/)) score++;

        //if password has at least one special caracther give 1 point
        if ( password.match(/.[!,@,#,$,%,^,&,*,?,_,~,-,(,)]/) )	score++;

        //if password bigger than 12 give another 1 point
        if (password.length > 12) score++;

        $('.jsPasswordDescription').html(desc[score]);
        $('.jsPasswordStrength').removeAttr('class').addClass('jsPasswordStrength').addClass("strength" + score);
    }
</script>
