<ul id="tabDomainLogsList" class="unstyled jsLineColor">
    <? foreach ($this->html('logs') as $logId => $log): ?>
        <li id="tabDomainLogsListEntry-<?= $logId ?>" class="row-fluid cssLine jsLine">
            <span class="span2">
                <?= $log->html('datetime') ?>    
            </span>
            <span class="span8">
                <? $translateVars = array(); ?>
                <? foreach($log->html('messageVars') as $messageVar): ?>
                    <? array_push($translateVars, $messageVar); ?>
                <? endforeach; ?>

                <?= $this->translate((string) $log->html('message'), $translateVars) ?>
            </span>
            <span class="pull-right">
                <?= $log->html('user') ?>
            </span>
        </li>
    <? endforeach; ?>
</ul>