<ul id="tabDomainNodesList" class="unstyled jsLineColor cssTab">
    <? foreach ($this->html('nodes') as $nodeId => $node): ?>
        <li id="tabDomainNodesListEntry-<?= $nodeId ?>" class="row-fluid cssLine jsLine">
            <a href="<?= $this->url(array($node->html('name')), 'nodedetail') ?>"
               title="<?= $node->html('name') ?>" class="span8">
                <?= $node->html('name') ?>
            </a>
            <a href="#" class="pull-right jsModulesOnNode">
                <?= $this->translate('Modules') ?> (<?= count($node->html('usedModules')) ?>)
            </a>
            
            <div class="jsUserNodeDomains" style="display:none;">
            <? if($node->toBool('usedModules')): ?>
                <ul id="tabDomainNodesListModules-<?= $nodeId ?>" class="cssPopoverTabList unstyled pull-left">
                    <? foreach ($node->html('usedModules') as $module): ?>
                        <li>
                            <a href="<?= $this->url(array($module->html('name')), 'moduleDetail') ?>"
                               title="<?= $module->html('label') ?>" class="pull-left">
                                <span>
                                    <?= $module->html('label') ?>
                                </span>
                            </a>
                        </li>
                    <? endforeach; ?>
                </ul>
            <? endif; ?>
            </div>
        </li>
    <? endforeach; ?>
</ul>
<script type="text/javascript">
    $(document).ready(function() {
        $('.jsModulesOnNode').each(function() {
            var parentLi = $(this).closest('li');
            var content = $.trim($(parentLi).find('.jsUserNodeDomains').html());
            
            if(content) {
                $(this).popover({
                    placement: 'bottom',
                    content: content,
                    html: true,
                    trigger: 'click'
                });
            }
            
            $(this).click(function(){return false;});
        });
    });
</script>
