<form class="form-inline row-fluid cssAddService" id="formServices" method="post"
      action="<?= $this->url(array($this->html('domain/name')), 'addDomainService') ?>?format=json">
    <dl class="span12">
        <dt class="span3 text-right">
        <label>
            <?= $this->translate('Add new service') ?>
        </label>
        </dt>
        <dd class="span7">
            <?= $this->serviceForm->service ?>
            <input  class="btn btn-info" id="jsAddService"
                    type="submit" value="<?= $this->translate('ok') ?>" />
        </dd>
    </dl>
</form>
<li id="templateAddServiceTab" style="display:none;">
    <a class="link" data-toggle="tab" href="#templateAddServiceTabContent">
        <i class="icon-chevron-right text-right"></i>
        <i class="icon-trash text-right jsRemoveService"></i>
        <span></span>
    </a>
</li>
<div class="tabbable tabs-left row-fluid cssTabContentAll">
    <ul id="tabServiceList" class="nav nav-list unstyled cssTabMenuLeft span3">
    <? foreach($this->html('services') as $serviceName => $service): ?>
        <li>
            <a class="link" data-toggle="tab" href="#jsService<?= $serviceName ?>">
                <i class="icon-chevron-right text-right"></i>
                <i class="icon-trash text-right jsRemoveService"
                   module="<?= $service->html("label"); ?>" service="<?= $service->html("name"); ?>"></i>
                <span>
                    <?= strtoupper($service->html('label')); ?>
                <span>
            </a>
        </li>
    <? endforeach; ?>
    </ul>
    
    <div id="tabServiceContent" class="tab-content cssTabContent span9">
        <div id="templateAddServiceTabContent" class="tab-pane" style="display:none;">
            <?= $this->translate('No configuration available'); ?>
        </div>
        <div id='servicesLoadingIndicator' style='display:none;'>
            <img src="<?= $this->baseUrl() ?>/img/js/loading.gif">
        </div>
    <? foreach($this->services as $serviceName => $service): ?>
        <div id="jsService<?= $serviceName ?>" class="tab-pane"
        <? if($service->toBool('routes/config/domain/route')): ?>
             href='<?= $this->url(array('domainName' => $this->html('domain/name') ,
                                        'domainId' => $this->html('domain/_id')),
                     (string) $service->html('routes/config/domain/route')); ?>?format=html'
        <? endif; ?>>
            
        <? if(!$service->toBool('routes/config/domain/route')): ?>
            <?= $this->translate('No configuration available'); ?>
        <? endif; ?>
            
        </div>
    <? endforeach; ?>
    </div>
    <div id="jsConfirmDelete" class="modal hide fade">
        <div class="modal-body"><p></p></div>
        <div class="modal-footer">
            <a class="btn jsButtonCancel" data-dismiss="modal"><?= $this->translate("cancel"); ?></a>
            <a class="btn btn-primary jsButtonDelete" data-dismiss="modal"><?= $this->translate("ok"); ?></a>
        </div>
    </div>
</div>
<script type='text/javascript'>    
    $(document).ready(function() {

        initServiceTabClickEvent();
        $('#tabDomainServices a[data-toggle="tab"]:visible:first').click();
        
        $('#formServices').submit(function() {
            var service = $('#service').selectpicker('val');
            if(!service) {
                return false;
            }

            $.ajax({
                type: 'post',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function(data) {
                    if(data.status === true) {
                        $("#service").serviceSelect("del", service);
                        $("#tabServiceList:hidden").show();
                        if(data.service) {
                            addServiceTabEntry(data.service, data.configDomainRoute);
                        }
                    }
                    setMessages(data, true);
                }
            });
        
            return false;
        }).find('#service').attr('disabled', function(index, value){
            $('#jsAddService').attr('disabled', value);
        });
        
        $.fn.serviceSelect = function(action, service) {
            if (action === "add"){
                var option = $("<option />", {
                    value: (service.name || ""),
                    label: (service.label || null),
                    html : (service.label || null)
                });

                if (this.prop("disabled")){
                    this.attr("disabled", false)
                        .find("option").eq(0).text("<?= $this->translate("Add new service"); ?>");
                    $("#jsAddService").attr("disabled", false);
                }

                this[0].options.add(option[0], 0);
            }
            else if(action === "del") {
                this.find('option[value="' + service +'"]').remove();
                if(this.find("option").length <= 1) {
                    this.attr("disabled", true)
                        .find("option").eq(0)
                        .text("<?= $this->translate("No services available"); ?>");
                    $("#jsAddService").attr("disabled", true);
                }
            }

            return this.selectpicker("refresh").selectpicker("val", "");;
        };
    
        if ($("#tabServiceList li:visible").length === 0){
            $("#tabServiceList").hide();
        }
    });
    
    function initButtonDeleteEvent() {
        $(".jsRemoveService").click(function(e){
            var self = $(this);
            var dialog = $("#jsConfirmDelete").modal({backdrop: "static", show: true});
            var uri = "<?= $this->url(array($this->html("domain/name"), ""), "removeDomainService") ?>";
            e.preventDefault();
            dialog.find(".jsButtonDelete").unbind("click").click(function(){
            $.ajax({
                url: uri+ self.attr("service")+ "?format=json",
                success: function(data){
                    if (data && data.result === true) {
                        self.closest("[data-toggle='tab']:visible").fadeOut();
                        $(".jsTabServiceCount").text(parseInt($(".jsTabServiceCount").text()) -1);
                        $("#jsService" +self.attr("service")).fadeOut().remove();
                        $("#service").serviceSelect("add", {name: self.attr("service"), label: self.attr("module")});
                        $("#tabServiceList li[class!='active'] a[data-toggle='tab']:visible:first").click();
                    }
                    setMessages(data);
                }
            });dialog.modal("hide");
            }).andSelf().find(".jsButtonCancel").click(function(){
                dialog.modal("hide");
            });dialog.find("p").text('<?= $this->translate('Should the service %1$s be removed from the domain?'); ?>'.replace("%1$s", self.attr("module")));
        });
    }

    function initServiceTabClickEvent() {
        $('#tabDomainServices a[data-toggle="tab"]:visible').click(function (e) {
            e.preventDefault();
            var target = $($(this).attr('href'));
            if($(target).length > 0 && $(target).attr('href') && $(target).attr('loaded') !== "true") {
                $('#servicesLoadingIndicator').show();
                $(target).attr('loaded', true);
                
                $(target).load($(target).attr('href'), function(response, status) {
                    if (status === "error") {
                        var msg = "<?= $this->translate('Couldn\'t load service configuration') ?>";
                        $(target).html(msg);
                      }
                  
                    $('#servicesLoadingIndicator').hide();
                });
            }
        });
        initButtonDeleteEvent();
    }
    
    function addServiceTabEntry(service, url) {
        if($.isEmptyObject(service) || !service.label || !service.name) {
            return false;
        }
        
        var templateTab = $('#templateAddServiceTab').clone();
        var templateTabContent = $('#templateAddServiceTabContent').clone();

        if(service._id) {
            $(templateTab).find('a').attr('href', "#jsService" + service._id);
            $(templateTabContent).attr('id', "jsService" + service._id);
        } else {
            $(templateTab).find('a').attr('href', "#jsService" + service.name);
            $(templateTabContent).attr('id', "jsService" + service.name);
        }
        
        $(templateTab).find('a span').html(service.label.toUpperCase());
        
        if(url) {
            $(templateTabContent).html('').attr('href', url + '?format=html');
        }

        $(templateTab).appendTo('#tabServiceList').removeAttr('style');
        $(templateTabContent).appendTo('#tabServiceContent').removeAttr('style');
        $(".jsTabServiceCount").text(parseInt($(".jsTabServiceCount").text()) +1);
        $('[href="#jsService' +service.name+ '"]').find(".jsRemoveService").attr("module", service.label).attr("service", service.name);

        initServiceTabClickEvent();
        
        $('.jsTabServiceCount').html($('#tabDomainServices a[data-toggle="tab"]:visible').length);
        
        if($('#tabDomainServices a[data-toggle="tab"]:visible').length === 1) {
            $('#tabDomainServices a[data-toggle="tab"]:visible:first').click();
        }
        
        return true;
    }
</script>
