<div class="cssContentMiddle grid_16">
    <ul class="grid_16 cssInstallStep">
        <li class="grid_4 cssInstallStep1 active">
            <?= $this->translate('create database') ?>
        </li>
        <li class="grid_4 cssInstallStep2">
            <?= $this->translate('Create administrator') ?>
        </li>
        <li class="grid_4 cssInstallStep3">
            <?= $this->translate('start the installation') ?>
        </li>
        <li class="grid_4 cssInstallStep4">
            <?= $this->translate('completion') ?>
        </li>
    </ul>
    <div class="cssDetailPadding30 cssForm grid_16">
        <h1>
             <?= $this->translate('database installation') ?>
        </h1>
        <div class="cssFormBoxLong grid_16">
            <form method="post" action="<?= $this->url(array(), 'installDatabase') ?>">
                <dl class="grid_16">
                    <?= $this->form->database ?>
                </dl>
                <dl class="grid_16">
                    <?= $this->form->collectionPrefix ?>
                </dl>
                <dl class="grid_16">
                    <dt id="connection-label">
                        <label><?= $this->form->host->getLabel(); ?></label>
                    </dt>
                    <dd id="connection-element">
                        <div class="grid_16 ">
                            <div class="grid_3"><?= $this->form->host->renderViewHelper(); ?></div>
                            <div class="grid_4"><?= $this->form->port->renderViewHelper(); ?></div>
                        </div>
                    </dd>
                </dl>
                <dl class="grid_16">
                    <?= $this->form->username; ?>
                </dl>
                <dl class="grid_16">
                    <?= $this->form->password; ?>
                </dl>
                <div class="grid_16 cssButtonSpace cssButtonNew">
                    <input class="cssButton jsButton" type="submit" value="<?= $this->translate('more') ?>" />
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.jsButton').button();
    });
</script>