<div class="cssContentMiddle grid_16">
    <ul class="grid_16 cssInstallStep">
        <li class="grid_4 cssInstallStep1 active cssStepComplete">
            <?= $this->translate('create database') ?>
        </li>
        <li class="grid_4 cssInstallStep2 active cssStepComplete">
            <?= $this->translate('Create administrator') ?>
        </li>
        <li class="grid_4 cssInstallStep3 active cssStepComplete">
            <?= $this->translate('start the installation') ?>
        </li>
        <li class="grid_4 cssInstallStep4 active">
            <?= $this->translate('completion') ?>
        </li>
    </ul>
    <div class="cssDetailPadding30 cssForm grid_16">
        <h1>
            <?= $this->translate('the installation could not be completed') ?>
        </h1>
        <div class="cssFormBoxLong grid_16">
            <p class="cssFont">
                <?= $this->translate('please correct the error and restart the installation') ?>
            </p>
            <div class="grid_16 cssButtonSpaceLeft cssButtonNew">
                <a href="<?= $this->url(array(), 'installIndex') ?>"
                   class="jsButton">
                    <?= $this->translate('installation repeat') ?>
                </a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.jsButton').button();
    });
</script>