<div class="cssContentMiddle grid_16">
    <ul class="grid_16 cssInstallStep">
        <li class="grid_4 cssInstallStep1 active cssStepComplete">
            <?= $this->translate('create database') ?>
        </li>
        <li class="grid_4 cssInstallStep2 active cssStepComplete">
            <?= $this->translate('Create administrator') ?>
        </li>
        <li class="grid_4 cssInstallStep3 active">
            <?= $this->translate('start the installation') ?>
        </li>
        <li class="grid_4 cssInstallStep4">
            <?= $this->translate('completion') ?>
        </li>
    </ul>
    <div class="cssDetailPadding30 cssForm grid_16">
        <h1>
            <?= $this->translate('summary') ?>
        </h1>
        <div class="cssFormBoxLong grid_16">
            <dl class="grid_16">
                <dt>
                    <label>
                        <?= $this->translate('Database Name'); ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->html('config/dbName'); ?>
                    </span>
                </dd>
            </dl>
            <dl class="grid_16">
                <dt>
                    <label>
                        <?= $this->translate('Database Server'); ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->toBool('config/host') ? $this->html('config/host') : MongoDb_Mongo::DEFAULT_HOST; ?> :
                        <?= $this->toBool('config/port') ? $this->html('config/port') : MongoDb_Mongo::DEFAULT_PORT; ?>
                    </span>
                </dd>
            </dl>
            <dl class="grid_16">
                <dt>
                    <label>
                        <?= $this->translate('Database Prefix'); ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->html('config/dbCollectionPrefix'); ?>
                    </span>
                </dd>
            </dl>
            <dl class="grid_16">
                <dt>
                    <label>
                        <?= $this->translate('Database User'); ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->html('config/dbUsername'); ?>
                    </span>
                </dd>
            </dl>
            <dl class="grid_16">
                <dt>
                    <label>
                        <?= $this->translate('Database Password'); ?>
                    </label>
                </dt>
                <dd>
                    <span>******</span>
                </dd>
            </dl>
             <dl class="grid_16">
                 <dt>
                    <label>
                        <?= $this->translate('admin e-mail') ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->html('config/email'); ?>
                    </span>
                </dd>
            </dl>
             <dl class="grid_16">
                 <dt>
                    <label>
                        <?= $this->translate('admin user name') ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->html('config/username'); ?>
                    </span>
                </dd>
            </dl>
            <dl class="grid_16">
                <dt>
                    <label>
                        <?= $this->translate('company') ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->html('config/company'); ?>
                    </span>
                </dd>
            </dl>
            <dl class="grid_16">
                <dt>
                    <label>
                        <?= $this->translate('Security Key') ?>
                    </label>
                </dt>
                <dd>
                    <span>
                        <?= $this->html('config/securekey'); ?>
                    </span>
                </dd>
            </dl>
            <? if ($this->toBool("reconfigInvalid")): ?>
            <div class="grid_16 cssButtonSpaceLeft cssButtonNew">
                <a href="<?= $this->url(array(), 'installIndex') ?>"
                   class="jsButton">
                    <?= $this->translate('installation repeat') ?>
                </a>
            </div>
            <? else: ?>
            <div class="grid_16 cssButtonSpaceLeft cssButtonNew">
                <a href="<?= $this->routeComplete; ?>"
                    class="jsButton">
                    <?= $this->translate('installation complete') ?>
                </a>
            </div>
            <? endif; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.jsButton').button();
    });
</script>









        
