<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid ">
            <div class="cssUserImage span2">
                <img name="avatar" class="img-polaroid" src="<?= $this->baseUrl() ?>/img/dummy_domain_200.png" alt="<?= $this->translate('avatar') ?>">
            </div>
            <form class="span10" action="<?= $this->url(array(), 'addDomain') ?>" method="post">
                <dl class="row-fluid">
                    <dt class="span3">
                    <label><?= $this->translate('domain name *') ?></label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->name ?>
                    </dd>
                    
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label><?= $this->translate('domain of client *') ?></label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->owner ?>
                    </dd>
                    
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label><?= $this->translate('procurement place') ?></label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->procurementplace ?>
                    </dd>
                </dl>
                <div class="row-fluid">
                    <input id="jsCancelButton" class="btn btn-info" type="reset" value="<?= $this->translate('cancel') ?>" />
                    <input class="btn btn-info jsButton" type="submit" value="<?= $this->translate('save') ?>" />
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#jsCancelButton').click(function() {
            location.href = '<?= $this->url(array(), 'domains'); ?>';
        });
    });
</script>