<div class="row-fluid">
    <div class="span12" ng-controller="DomainController">
        <div class="row-fluid text-left cssBoxCenter">
            <a ng-click="delete($event);" href="<?= $this->url(array($this->html("domain/name")), "deleteDomain") ?>"
               class="jsIconDeleteTxt btn" title="<?= $this->translate("delete domain"); ?>">
                <i class="icon-trash"></i> <?= $this->translate("delete"); ?>
            </a>
        </div>
        <div class="row-fluid cssBoxCenter">
            <div class="span10">
                <div class="row-fluid">
                    <div class="cssUserImage span2">
                        <img name="avatar" class="img-polaroid"
                             src="<?= $this->baseUrl() ?>/img/dummy_domain_200.png"
                             alt="<?= $this->translate('avatar') ?>">
                    </div>

                    <div class="span9 offset1">
                        <form action="<?= $this->url(array(), 'domaindetail') ?>" method="post">
                            <dl class="row-fluid cssBigItem">
                                <span class="span9">
                                    <?= $this->form->name ?>
                                </span>
                            </dl>
                            <dl class="row-fluid">
                                <dt class="span3">
                                <label>
                                    <?= $this->translate('Client') ?>
                                </label>
                                </dt>
                                <dd class="span6">
                                    <a href="<?= $this->url(array($this->html('owner/_id'), $this->html('owner/label')), 'clientDetail') ?>">
                                        <?= $this->html('owner/label') ?>
                                    </a>
                                </dd>
                            </dl>
                            <dl class="row-fluid">
                                <dt class="span3">
                                <label>
                                    <?= $this->translate('procurement place') ?>
                                </label>
                                </dt>
                                <dd class="span6">
                                    <?= $this->form->procurement ?>
                                </dd>
                            </dl>
                        </form>
                    </div>
                </div>
                <div class="row-fluid" id="additionalFieldsContent">
                    <maze-additional fields="domain" update="update($data)"></maze-additional>
                </div>
            </div>
        </div>
        <div class="row-fluid cssBoxCenter">
            <div class="span12">
                <ul class="nav nav-tabs unstyled" id="tabsDomain">
                    <li id="tabTitleDomainServices" class="active">
                        <a data-toggle="tab" href="#tabDomainServices">
                            <?= $this->translate("Services"); ?> (<span class="jsTabServiceCount"><?= count($this->html('services')) ?></span>)
                        </a>
                    </li>
                    <li id="tabTitleDomainClients">
                        <a data-toggle="tab" href="#tabDomainNodes">
                            <?= $this->translate("Nodes"); ?> (<span class="jsTabNodeCount"><?= count($this->nodes) ?></span>)
                        </a>
                    </li>
                    <li id="tabTitleDomainLogs">
                        <a data-toggle="tab" href="#tabDomainLogs">
                            <?= $this->translate("log"); ?>
                        </a>
                    </li>
                </ul>

                <div class="tab-content cssTabContentOuter row-fluid">
                    <div class="active tab-pane" id="tabDomainServices">
                        <?= $this->render('domains/tabs/services.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabDomainNodes">
                        <?= $this->render('domains/tabs/nodes.phtml'); ?>
                    </div>
                    <div class="tab-pane cssTabContentAll" id="tabDomainLogs">
                        <?= $this->render('domains/tabs/logs.phtml'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <script type="text/ng-template" id="ModalDomainDelete.html">
        <div class="modal-header" ng-if="modal.title;">
            <h3 class="modal-title">{{modal.title}}</h3>
        </div>
        <div class="modal-body" ng-if="modal.body;">
            <p>{{modal.body}}</p>
        </div>
        <div class="modal-footer">
            <button class="btn" ng-click="dismiss();"><?= $this->translate("cancel"); ?></button>
            <button class="btn btn-primary" ng-click="confirm();"><?= $this->translate("ok"); ?></button>
        </div>
    </script>
</div>
<script type="text/javascript">

    app.controller('DomainController', ['$scope', '$modal', 'domainsService', function($scope, $modal, domainsService){
        $scope.domain = {_id: "<?= $this->html("domain/_id"); ?>"};

        $scope.update = function(data){
            return domainsService.update($scope.domain._id, data).success(function(response){
                $scope.domain = response;
            });
        };

        $scope.delete = function(event){
            modal().result.then(function (){
                domainsService.delete($scope.domain._id).success(function(response, status){
                    if (status === 202) {
                        return location.href = "<?= $this->url(array(), "domains"); ?>";
                    }
                });
            });

            return event.preventDefault();
        };

        var modal = function(){
            return($modal.open({
                templateUrl: "ModalDomainDelete.html",
                controller : function ($scope, $modalInstance){
                    $scope.modal = {
                        body: "<?= $this->translate("Shall the domain really be deleted?"); ?>"
                    };
                    $scope.confirm = $modalInstance.close;
                    $scope.dismiss = function (){
                        $modalInstance.dismiss("cancel");
                    };
                }
            }));
        };

        domainsService.get($scope.domain._id).success(function(response){
            $scope.domain = response;
        });
    }]);

    $(document).ready(function() {

<? foreach ($this->html("services") as $service): ?>
    <? if ($service->html("route/config/domain") != ""): ?>
        $.post("<?= $this->url(array($this->html("domainId")), (string) $service->html("route/config/domain")); ?>", {format: "html"}, function(data){
            $(data).appendTo(".jsService");
        });
    <? endif; ?>
<? endforeach; ?>

    });
</script>
