<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid cssListing">
            <div class="span12 cssHeaderList">
                <div class="cssButton span12">
                    <a class="btn btn-info jsButton" href="<?= $this->url(array(), 'addDomain') ?>">
                        <?= $this->translate('Create domain') ?>
                    </a>
                </div>
            </div>
        </div>
        
        <?= $this->render('shared/pager.phtml') ?>
        
        <div id="domainListing" class="row-fluid cssListing">
            <ul class="span12 unstyled">
                <li class="row-fluid">
                    <div class="offset10 span2 cssAction"></div>
                </li>
                
            <? foreach($this->html('pager/data') as $domain): ?>
                <li class="row-fluid">
                    <div class="span10">
                        <a class="cssListItem span12" title="<?= $this->translate('detail') ?>"
                            href="<?= $this->url(array($domain->html('_id')), 'domaindetail')?>">
                            <span class="cssAvatar">
                                <img src="<?= $this->baseUrl() ?>/img/dummy_domain_50.png" alt="<?= $this->translate('avatar') ?>"/>
                            </span>
                            <span><?= $domain->html('name') ?></span>
                        </a>
                    </div>
                    <div class="span2 cssAction"></div>
                </li>
            <? endforeach; ?>
            </ul>
        </div>
        <div id="jsConfirmDelete" class="modal hide fade">
            <div class="modal-body">
                <p><?= $this->translate('Shall the domain really be deleted?') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn jsButtonCancel" data-dismiss="modal"><?= $this->translate('cancel') ?></a>
                <a class="btn btn-primary jsButtonDelete" data-dismiss="modal"><?= $this->translate('ok') ?></a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#coreSearchCategorySelected').html($('#coreSearchCategoryDomains').html());
        $('#coreSearchCategoryList a').removeAttr('checked');
        $('#coreSearchCategoryDomains').attr('checked', 'checked');

        $('#coreSearchInput').mazeSearch('option', 'source', '<?= $this->url(array(), 'domains') ?>?format=html');
        $('#coreSearchInput').mazeSearch('option', 'page', '<?= $this->html('pager/page') ?>');
    });
</script>
