<script type="text/javascript">
    angular.module('maze').config(['$routeProvider',function($routeProvider) {
        $routeProvider.
            when('/', {
                templateUrl: '/partials/admin/domains/list.html',
                controller: 'domainListController'
            }).
            when('/edit/:domainId', {
                templateUrl: '/partials/admin/domains/edit.html',
                controller: 'domainEditController'
            }).
            when('/new', {
                templateUrl: '/partials/admin/domains/new.html',
                controller: 'domainNewController'
            });
    }]);
</script>

<div class="row-fluid">
    <div ng-view></div>
</div>