<div class="row-fluid" id="jsAdmin">
    <div class="span12">
        <div class="row-fluid ">
            <div class="cssUserImage span2">
                <img class="img-polaroid" name="avatar" src="<?= $this->baseUrl() ?>/img/dummy_admin_200.png" alt="<?= $this->translate('avatar') ?>">
            </div>
            <form class="span10" action="<?= $this->url(array(), 'addAdministrator') ?>" method="post" id="jsAddAdmin">
                <dl class="row-fluid">
                    <dt class="span3">
                    <label>
                        <?= $this->translate('E-mail address *') ?>
                    </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->email ?>
                    </dd>
                </dl>
                <h6><?= $this->translate('access data') ?></h6>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label>
                        <?= $this->translate('username *') ?>
                    </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->username ?>
                    </dd>
                </dl>
                <dl class="row-fluid">
                    <dt class="span3">
                    <label>
                        <?= $this->translate('password *') ?>
                    </label>
                    </dt>
                    <dd class="span9">
                        <?= $this->form->password ?>
                    </dd>
                </dl>
                <div class="row-fluid">
                    <input id="jsCancelButton" class="btn btn-info" type="reset" value="<?= $this->translate('cancel') ?>" />
                    <input class="btn btn-info" type="submit" value="<?= $this->translate('save') ?>" />
                </div>
            </form>
            
        </div>
    </div>
</div>

<?= $this->render('shared/passwordStrength.phtml'); ?>

<script type="text/javascript">
    $(document).ready(function() {
        $('#jsCancelButton').click(function() {
            window.history.back()
        });

        $("form#jsAddAdmin").submit(function(event){

            $.ajax({
                url:  this.action,
                type: this.method,
                data: $(this).serializeArray(),
                success: function(data){
                    if ($(data).find(".alert.alert-error").length) {
                        $("#jsAdmin").html(data)
                    } else if ($(data).find("#createadmin").length) {
                        window.location = "#/system/"
                    }
                }
            });

            event.preventDefault();
        });

        setPasswordStrength("#password");
    });
</script>
